apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:SqxT9c2xpWU=,iv:Hrah4AlZpLAUOFqS1IiXrOBt4o2ICzm3H05GXHKLEB8=,tag:yGDzGU6ZMyRrQI3048CytQ==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:A9uG2WFfriLLPHqV,iv:WKPTQ0vxx1VE4ttdj5gHSLM6EdWq84S/7ml8gSjs134=,tag:GVeBxuxwCyjkMvwOY44fdA==,type:str]
    AWS_ACCESS_KEY: ""
    AWS_SECRET_ACCESS_KEY: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNE5ZbTVWU2N5V3ZGanpk
            cE1mTDFEMDUzdkVsT2Y1MThxODRydklRUFdNCk8weXZleHQ2WEtrOTV6NzNYT05L
            dFhuSks3cGJMZHJkTmhxK0FpVTU4eU0KLS0tIFM5K292MFlpc05idGIvQUNnYUhl
            aEkvZ09aYUlrTHRtM1F2aUxuREtjZ28KLoF8lNMlatujX/0R98MhlNfdkx7YCuLK
            PpT4lnpBeeAuq/cMPqL38r2VJBp/1ZNl2oUoGimmVmtu8bz2oRM4/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-24T14:14:10Z"
    mac: ENC[AES256_GCM,data:h06XZvnQwzZ/vuP5igrmCOVFBoau0YyPK7bWEh7IBrOpv2O/qH36gWquuNRASWpsfHrN2xL0sRu2WXBWVqcHMdX3Ld9/MtWxUyqPy36FWS+iyOTEm9gR4usiGQlYyYBtgGKYMzBlG1JF3CP3L9pRRHs8PqBLEld2jHqzf0YRyRI=,iv:D2C2IkpVwVARJcE2q4EBysWJs34SNYi2704Uq3sgboQ=,tag:bvC+t0ZsLo8jZJ6ZCHcRnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
