---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omegabrr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/autobrr/omegabrr
      tag: v1.8.0
    env:
      TZ: "${TZ}"
      PUID: "1000"
      PGID: "1000"
    service:
      main:
        ports:
          http:
            port: 7441
    persistence:
      config:
        enabled: true
        type: secret
        name: omegabrr-secret
        subPath: config.yaml
        mountPath: /config/config.yaml
        readOnly: true
