---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: omegabrr-config-tpl
    files:
      - ./configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: omegabrr
      app.kubernetes.io/instance: omegabrr
