---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tubearchivist-elasticsearch
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 0
        fsGroup: 0

    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.elastic.co/elasticsearch/elasticsearch
              tag: 8.11.2
            env:
              TZ: "${TZ}"
              ES_JAVA_OPTS: -Xms2G -Xmx2G
              xpack.security.enabled: "true"
              discovery.type: single-node
              path.repo: /usr/share/elasticsearch/data/snapshot
            envFrom:
              - secretRef:
                  name: tubearchivist-secret
            resources:
              requests:
                cpu: 22m
                memory: 760M
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: longhorn
              globalMounts:
                - path: /usr/share/elasticsearch/data

    service:
      main:
        ports:
          http:
            port: 9200
