---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tubearchivist-elasticsearch
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - targetPath: env.ELASTIC_PASSWORD
      kind: Secret
      name: tubearchivist-secret
      valuesKey: ELASTIC_PASSWORD
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: elasticsearch
      tag: 8.8.1
    env:
      TZ: "${TZ}"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: "true"
      discovery.type: single-node
      path.repo: /usr/share/elasticsearch/data/snapshot
    service:
      main:
        ports:
          http:
            port: 9200
    volumeClaimTemplates:
      - name: config
        mountPath: /usr/share/elasticsearch/data
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: longhorn
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 1000Mi
