---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/larivierec/bitwarden-cli
              tag: 2024.9.0
            envFrom:
              - secretRef:
                  name: bitwarden-cli
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command: ["sh", "-c", "curl -X POST -s http://127.0.0.1:8087/sync | jq -e '.success == true'"]
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: false
            resources:
              requests:
                memory: 256Mi
                cpu: 100m

    service:
      main:
        controller: main
        ports:
          http:
            port: 8087

    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /.config
