---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 15m
  chart:
    spec:
      chart: rancher-stable
      version: 2.7.3
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: cattle-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hostname: rancher.tostava.com
    ingress:
      enabled: true
      ingressClassName: nginx
      extraAnnotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    resources:
      requests:
        cpu: 100m
        memory: 128M
