---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/joryirving/qbittorrent
              tag: 5.1.2@sha256:4f36229a58558add3d385f5d8a81bae110e55f03654b7dc73a90208e06a16bb8
            env:
              TZ: "${TZ}"
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &port-bt "${SECRET_VPN_FORWARDED_PORT_1}"
            resources:
              requests:
                cpu: 25m
                memory: 1G
        pod:
          hostname: qbittorrent
          annotations:
            setGateway: "true"
        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              accessMode: "ReadWriteOnce"
              size: 1Gi
              storageClass: longhorn

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: qbittorrent.png
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/group: Downloads
          gethomepage.dev/description: qBittorrent is a free and open-source BitTorrent client.
          gethomepage.dev/widget.type: qbittorrent
          gethomepage.dev/widget.url: http://qbittorrent.downloads:80
          gethomepage.dev/widget.username: ${SECRET_QBITTORRENT_USERNAME}
          gethomepage.dev/widget.password: ${SECRET_QBITTORRENT_PASSWORD}
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          authentik.home.arpa/enabled: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        existingClaim: downloads
        globalMounts:
          - path: /data
