---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./media-pvc.yaml
  - ./media-old-pvc.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
