---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-old
spec:
  capacity:
    storage: 24T
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NAS_IP}
    path: /mnt/tank/media
  mountOptions:
    - hard
    - intr
    - nconnect=8
    - nfsvers=4.1
    - noacl
    - nocto
    - relatime
    - rsize=131072
    - tcp
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-old
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  volumeName: media-old
  storageClassName: ""
  resources:
    requests:
      storage: 24T
