---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-longhorn
  namespace: flux-system
spec:
  path: ./kubernetes/apps/longhorn/longhorn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  interval: 15m
  retryInterval: 5m
  timeout: 5m
