---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  refreshInterval: 5m
  target:
    name: n8n
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: e55b801e-f7ea-4607-977c-b2c800c2551e
        property: N8N_ENCRYPTION_KEY
