---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tdarr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/downloads/tdarr/tdarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: tdarr
      namespace: downloads
  interval: 30m
  retryInterval: 1m
  timeout: 3m
