kind: ENC[AES256_GCM,data:KdSBGaEv,iv:01goXsucby0DbIpBj+n58hGS0/m9jUdWvGWPYt7CRtA=,tag:d/3Q0urionVpeNmNXYx6Xw==,type:str]
ansible_user: ENC[AES256_GCM,data:M0D9,iv:aE1TJ9jdCn6stIfip1GPxDKt0xd0SIA/hs/Kh0/1ojY=,tag:0IH9wngZXTno3eEcXbuS8g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:90F0t/cZzfw=,iv:hR+Dc9n6KarhcSRaV0PwkZwud3KmikYdh4/3GE1iqYs=,tag:NwTNJGRFPu6EMVtEci1t4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNi9NZUlRbmZGb0tud0Zw
            a2lIUitlamZuRG8wQlNianR0VkpmTzExL0JZCm5wanZTYjFnS0huV1lDTHV6THVD
            bU93b1BIa3JWeTB2U0FTcDU5c3dzazgKLS0tIHFrSmEzVmhpK3ByanNRR1JkNXp1
            SDRSUjRVUGxzZ1R2Qjl6NUJkYU5MckUKeWTholjjcMjMspPaO/tls7k7+njU4gRd
            qA4MJd8btZEsYA8kxTRrwewWxFG/ZsdrF7wyYs1OgYajVEVU1428tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T13:11:53Z"
    mac: ENC[AES256_GCM,data:bBClV1amqMbHu0nUMZEqfQ+MXOyv4p+fU4sRAtLMQgekBELhAm7KpgNMci5FTYo86NiOeg749DmQeL49HOUTxWAih+jonWjIrR4+ayg2W0zSXyx3V2Ano4/q0gMs/DDxumynbNSlF8Ij+fprzqKF6eGqHnkhehsroQRgyU38vls=,iv:vmTDQsYqPskrMEIVKu8+qg6JU7Ho+BbeO+YwnsFChD0=,tag:tcTQdfuHBo7ndpcYBtQy7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
