kind: ENC[AES256_GCM,data:mVir8e6z,iv:otuGZp9jEynyqkIXHeN4fss+VlZE/oTiHhAR0XgeFOw=,tag:xC0AHTP181YAA4vYfB9q2Q==,type:str]
ansible_user: ENC[AES256_GCM,data:CKEF,iv:Ckb6uLjFtgtGSzMvgNkHcoxuNohLTBd9H87dQ/D+9bg=,tag:UM+Gu+kIoGoJ1xwfIzu9kQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4i6As5WfFeg=,iv:/GI9OwZfUEKtmo22bIOYymtQwIftL7XbmcaawK9PO/E=,tag:F0oohuus1byYTSey6/DwwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXV05PZ0RFOGxPdVBQcXhw
            V0pJQ01zNmpyODhINXZ5aU9yV3IxdVpwR3prCnlrVjZyeHMwMjBHU2JGUWpVNDdI
            dFYwMHVSZkMzbnROY1Q1NDlZRU5DT2sKLS0tIHFnYURhMXo1WHRIbnFMZ0lUcTN4
            MnR1RFJPVnU3WWdkc1h4YzRYZlNybFUKNOj8E6cDRSr9YeNxbNKQQXCN8Q67ObUe
            nV9EDr/Q9U38SJSF8g6wxnc5Et6XDLdxtu4k1LV0BU4UyPQ1dj61mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T15:44:22Z"
    mac: ENC[AES256_GCM,data:byXICojHX9iOGCpiHn2tGJ4I9pZsdlZOhVgbYYzFisLF888aKkZzh9FNGKA9W0w2AR2f56m6BUlrZ5+/Cp4K8dVd2HG+zcKizH2/dlFt5Xy6uQW7aqLgR6kyhSRuyeBc/R+bCWKFwsWFmsMW+M4g8bxi2BaHPObFisbg55ulHlw=,iv:xHIpBvIF9EXkMd355cZgVp2wKjwgHPTxDFzNay2KhBc=,tag:surJCktGr+36lHkN14vvIA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
