kind: ENC[AES256_GCM,data:SFmN8LJu,iv:7GyUADAK9yqU8UMBTBpjwB/zxUCaUWKjCk5xDP0rmUs=,tag:8YQEPFlxH71pyBg2d3Cozw==,type:str]
ansible_user: ENC[AES256_GCM,data:Mg37,iv:KnKLZv0o3xkTaN2PFMz0MNpmvzcWZprk5HVCZQ7QOaM=,tag:wutV/dcfMCztXMJsklxwvQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:L/xOSmbkcEU=,iv:EdR/h71NpdvPXASZwTcIBgZEJh1BRgc17DMJE/D/8PA=,tag:usKWd/sJSm9FCcxCt6R3BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSUZMYnlObHJTVWJSL0xV
            MDY4VVRKcHExN1dRZ0ZrNmxkNWtjYmg3am44CmxTK3ROdDM1c3g5UFZFRUJuSDZl
            N3ZhYnlPUHR6T09jZXRyV2V6R1hjWkUKLS0tIDQ2SGR2dFlOak8vOVphQjdzZXJm
            MmZYQjZ0cEl5alFTZWJxT2Z4U2xwc0UK3xTWvKm4ZqKDhJ9t2oGYYay06BkTlFSb
            wRzU5NEhBQLoB6jJ01ikc3mxLrrma/Q+udd4bejBDQSHKtQQXB0E3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T21:39:11Z"
    mac: ENC[AES256_GCM,data:lL8rmeTP6htHEEkFZDjwHTzDleDian3MeOcQWQRUaONb39B9BbyV4MsDeVKfZwNAQcftBqBYZhenz0ahP5lmMbMZVp4FUeupQN7IF+fo+xfR6yhqz5lMxEKq3m+UKBmm7NanYyhr+0N8JcPFGPFJ2qRIsg+KyO3Wt8oV1MjKBvI=,iv:HjNF4ur53d2jJkouxNHiLZXmZ25laZH6UqlLNk0pWE4=,tag:8q1jAiQYkLzXM7ZVQu89WQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
