kind: ENC[AES256_GCM,data:ktoMtlgX,iv:BOX2zPOUwbw04sBI2ERoFZZfgNjNxWdi1Q6Pe+DCjME=,tag:T2KdKTINL02diqQv3NFXmA==,type:str]
ansible_user: ENC[AES256_GCM,data:AjRU,iv:xt68d+isHJvt7JDt3l2wvR31j5OPvi0HICZMZaQ+i00=,tag:pT0bTkyo7KksBAicbHowOw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:adj3CDWxk9o=,iv:yxBuKWEDYUsOPVJNh6MgshMYYEnUQN4MAYgYrEGEeZQ=,tag:cIJaI0v+Pf029gO09L7lKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3ljK05OdGRGT1ljakpp
            Vno3L1BIclc0cmRtd1RCRVdldWdwZXJGeEU4CmtLQ1JaV0oweFJvUmpEN3Y4elli
            M3pjUkQzT0Z3bHlYSHhUVE1FbGYxdlkKLS0tIGF0c0UrcDZ1cHhaZ0V2cVkrWTE2
            ejRGdnNKMGRpSFAxKzNHZ05MUzJYaHMK2UXSDZTweAwVH4gT0TTtNywSAme0OHe+
            J0fP49G5b+Tf3YX38mmjDsiCzUzHxTFQ9aM0dK5eXKbxp0tLPxcoUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T15:44:22Z"
    mac: ENC[AES256_GCM,data:hl6Z0sBCfkf6Pxk7tLNQSOWTFlAw+JcYRW84+2yORvSGpRkc/Aa96ivTCBfqjXxrWkOORCZUTi+0rpD0WB/3+DxX4qEJU39nDkrqqhuqS9Yo4fbihKQsXJ9TZICAL8aZbGK4KSBLFCZAcwLFG19V6rjWZ1n8hsgW1+dwiYhMdVU=,iv:9fRbr7FuPw8J7kCommlxZsGL11yLLzHAwlThG3NW3gQ=,tag:0LxvchoGaXA2FQyGKqxp3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
