kind: ENC[AES256_GCM,data:SoWB0zCK,iv:V5Z+kPuhNEFWqUUXPSVWwLwR/h9xM+6F7NfQTM4Ab/s=,tag:4Jpi2uJ1Z0new3pqpG8MJw==,type:str]
ansible_user: ENC[AES256_GCM,data:gGAA,iv:MfixmN/VUYGlXNkzFoGdxxsGTsNN6MHhUqmqLgcbrIk=,tag:eqObDC3N6vD3EorCAfkt5w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:T6FYIRvI37g=,iv:lS1lT8/tTzxbha+hQIqIUWG+6b4Xnj3aiZQGEG0SWt0=,tag:Ouh4h0y+3uFklMFQHniUwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUlJsRDBNK01QWnFUdjNr
            ZCs2bHlvdEtPUFdBRkhOS0pQc1U3dWVIT1J3Clk2WUVaZ1R6UysvbGRycnZROHFu
            aE10SUM0MGdUY2Zjb285c3M3NS9kSXMKLS0tIFh4aVdLQVlvdEhGVCt0UzBTdUV4
            VDFhcVYzTUl0OVdDSmtHZjJybitEM0EKKMXHqUgD70jsipXdrt16XMOduxIkwcIz
            OhTUUnyk3Cd2IcmGUeEBXEqQcPfJj/gdLXD+KQh5JeFzTXC2RnUjSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T15:44:22Z"
    mac: ENC[AES256_GCM,data:8/IYQW1523J4UtPXUIrI2yXMGHY4E4U8CamLWLfkWy54bwXVqxGSPG/IEAwX8LFO4kBGBaA66dmi+xeH62zviS5LJ24t03IEMVV9QWMwkOYEC/w2QwchKxAmjl3yhTnLPIUCGH0rjYefM+fIcUgLSvYhTqSs9tFkbNDIhov99WM=,iv:Zhox7tWd3tYQ6EoNJKnHBAPdE613zPXWI0ag/9e5l+c=,tag:s4O2eD58ONxbt1rML6O0zw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
