---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-node
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: daemonset
    image:
      repository: ghcr.io/haveagitgat/tdarr_node_acc
      tag: 2.00.20.1
    env:
      TZ: "${TZ}"
      PUID: "568"
      PGID: "568"
      ffmpegPath: "/usr/local/bin/ffmpeg"
      nodeName:
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    service:
      main:
        enabled: false
        ports:
          enabled: false
          http:
            port: 8265
    volumeClaimTemplates:
      - name: config
        mountPath: /app/config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
    persistence:
      media:
        enabled: true
        existingClaim: downloads
        mountPath: /mnt/media
        subPath: media
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      capabilities:
        add:
          - CHOWN
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
