---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr-node
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: daemonset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/haveagitgat/tdarr_node_acc
              tag: 2.42.01
            env:
              TZ: "${TZ}"
              PUID: "568"
              PGID: "568"
              serverIP: tdarr.downloads.svc.cluster.local
              serverPort: 8266
              ffmpegPath: "/usr/local/bin/ffmpeg"
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 568
              capabilities:
                add:
                  - CHOWN
            probes:
              startup:
                enabled: false
              liveness:
                enabled: false
              readiness:
                enabled: false
    service:
      main:
        controller: main
        enabled: false
        ports:
          http:
            enabled: false
            port: 8265

    persistence:
      media:
        enabled: true
        existingClaim: downloads
        globalMounts:
          - path: /data
