---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &app volsync
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: *app
      app.kubernetes.io/instance: *app
