---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: v3.0.3
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  values:
    controller:
      image:
        tag: v3.0.3
    webhook:
      image:
        tag: v3.0.3
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
