---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kibana
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-elasticsearch
  path: ./kubernetes/apps/elastic-system/kibana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
