apiVersion: v1
kind: Secret
metadata:
    name: grafana-github-secret
    namespace: monitoring
stringData:
    GF_AUTH_GITHUB_CLIENT_ID: ""
    GF_AUTH_GITHUB_CLIENT_SECRET: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbzB2Z3E5QVZBUW9IWVVZ
            eUNjd1VvSXNHZHBxQ3ZveFhURWJ2bVBweFdBCnFTMEtTRW5wZWoxV0lib1UxdGts
            RFk3OHJQRndBRHpTY0tBTEZ6THFTSFUKLS0tIEpQaURjTnlWQ0JoZkNOWG10L3Fo
            Q1ozUE5xSXZvTnRuSjRSTUdpM3VvSzgKDX/Av0dlHgG7hihdcCmcoVIsecIg7VHZ
            naO3POZfwrvwCoM2cUGzS4zs4hjxX6W3mUfqUTdxhCb23nIuW5FyRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T20:02:47Z"
    mac: ENC[AES256_GCM,data:b/Lrdp9YqSVC2+/c0/2P8xpHzpPmoF2BUbNQklV0VMGoNdLdNBxaSRiJaPCypE5+TLYD/oC+nf2qnmxU1M5pAI1q1giNyevvqtGk4tz4F1QrASDZ7ltaOhp9ZCztsVqUPqKAKIxn+NBsKsAd2wCMQjxwsmAqDFDOTLGu84YaLZs=,iv:ODaroEKwllEEj/MXJc29kmGk/2lSj1L25OjrQWG9QU8=,tag:nOhxFS+6z4O4TcYf1IuaZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-authentik-secret
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:k2GDeXVY6SMzExRMewHJfmTbTJasjZuz8gE0PdPossFzQy8eQQ8BpQ==,iv:Nt6EJFlpZUjk2VBTSVMWXPkP0wNuxB/MrUC5Slmei+s=,tag:YbsAl3/Ve5Wj0OMTCJvAJQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:TWxaJ6vqcWyG8u2IVyx/Y+q8c2VQqb3SyHkV+6Yhmtl5fgo62/+TsqwDRtO8AqERQ2bacoYlhvU7TMnE3Ih17agtH+rGaChrm6OPuduo0HmSO5Ner0+ViwKIB0Eh3K4zae7/kVT27dC3aUUfLWvtmwP7OgSsW2NBThW+y4uP9Qc=,iv:81Mab2dJRFvpVkZz1uzIfLsPRax2zFESnLGr4DfxNSQ=,tag:dS8Ej+VHqxxFz4AM13IU9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbzB2Z3E5QVZBUW9IWVVZ
            eUNjd1VvSXNHZHBxQ3ZveFhURWJ2bVBweFdBCnFTMEtTRW5wZWoxV0lib1UxdGts
            RFk3OHJQRndBRHpTY0tBTEZ6THFTSFUKLS0tIEpQaURjTnlWQ0JoZkNOWG10L3Fo
            Q1ozUE5xSXZvTnRuSjRSTUdpM3VvSzgKDX/Av0dlHgG7hihdcCmcoVIsecIg7VHZ
            naO3POZfwrvwCoM2cUGzS4zs4hjxX6W3mUfqUTdxhCb23nIuW5FyRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T20:02:47Z"
    mac: ENC[AES256_GCM,data:b/Lrdp9YqSVC2+/c0/2P8xpHzpPmoF2BUbNQklV0VMGoNdLdNBxaSRiJaPCypE5+TLYD/oC+nf2qnmxU1M5pAI1q1giNyevvqtGk4tz4F1QrASDZ7ltaOhp9ZCztsVqUPqKAKIxn+NBsKsAd2wCMQjxwsmAqDFDOTLGu84YaLZs=,iv:ODaroEKwllEEj/MXJc29kmGk/2lSj1L25OjrQWG9QU8=,tag:nOhxFS+6z4O4TcYf1IuaZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
stringData:
    adminUser: ENC[AES256_GCM,data:lA4d,iv:DD0wrcbW76aD3/nHXEkSiWx0SCwShHpWOoMqPtc2ejo=,tag:j4LaajdklmQ4jMUMUi0umw==,type:str]
    adminPass: ENC[AES256_GCM,data:upVOlnEPo+LDGt3+,iv:lyOumDfG/nHCP1qw5Okp7wVu1vEFmSVmXDHn7mutJho=,tag:V6KbXsz5TBklabqlLMbyqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbzB2Z3E5QVZBUW9IWVVZ
            eUNjd1VvSXNHZHBxQ3ZveFhURWJ2bVBweFdBCnFTMEtTRW5wZWoxV0lib1UxdGts
            RFk3OHJQRndBRHpTY0tBTEZ6THFTSFUKLS0tIEpQaURjTnlWQ0JoZkNOWG10L3Fo
            Q1ozUE5xSXZvTnRuSjRSTUdpM3VvSzgKDX/Av0dlHgG7hihdcCmcoVIsecIg7VHZ
            naO3POZfwrvwCoM2cUGzS4zs4hjxX6W3mUfqUTdxhCb23nIuW5FyRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T20:02:47Z"
    mac: ENC[AES256_GCM,data:b/Lrdp9YqSVC2+/c0/2P8xpHzpPmoF2BUbNQklV0VMGoNdLdNBxaSRiJaPCypE5+TLYD/oC+nf2qnmxU1M5pAI1q1giNyevvqtGk4tz4F1QrASDZ7ltaOhp9ZCztsVqUPqKAKIxn+NBsKsAd2wCMQjxwsmAqDFDOTLGu84YaLZs=,iv:ODaroEKwllEEj/MXJc29kmGk/2lSj1L25OjrQWG9QU8=,tag:nOhxFS+6z4O4TcYf1IuaZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
