---
kubernetes:
  children:
    master:
      hosts:
        k3s-master-1:
          ansible_host: 192.168.1.91
        k3s-master-2:
          ansible_host: 192.168.1.92
        k3s-master-3:
          ansible_host: 192.168.1.93
    worker:
      hosts:
        k3s-worker-1:
          ansible_host: 192.168.1.94
        k3s-worker-2:
          ansible_host: 192.168.1.95
        k3s-worker-3:
          ansible_host: 192.168.1.96
