---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  TZ: Europe/Oslo
  LOG_LEVEL: log
  NODE_ENV: production

  DB_DATABASE_NAME: &app immich
  DB_HOSTNAME: immich-postgres.media.svc.cluster.local
  DB_USERNAME: *app

  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003

  REDIS_HOSTNAME: immich-dragonfly.media.svc.cluster.local

  TYPESENSE_HOST: immich-typesense.media.svc.cluster.local
  TYPESENSE_DATA_DIR: /config
