---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  TZ: Europe/Oslo
  NODE_ENV: production
  LOG_LEVEL: log

  DB_HOSTNAME: immich-postgres
  DB_USERNAME: postgres
  DB_DATABASE_NAME: immich
  REDIS_HOSTNAME: immich-dragonfly
