---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  TZ: Europe/Oslo
  LOG_LEVEL: log
  NODE_ENV: production

  DB_PORT: "5432"
  DB_HOSTNAME: &dbhost immich-postgres.media.svc.cluster.local
  DB_DATABASE_NAME: &app immich
  DB_USERNAME: *app

  INIT_POSTGRES_DBNAME: *app
  INIT_POSTGRES_HOST: *dbhost
  INIT_POSTGRES_USER: *app

  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003

  REDIS_URL: ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJpbW1pY2gtZHJhZ29uZmx5Lm1lZGlhLnN2Yy5jbHVzdGVyLmxvY2FsIiwicG9ydCI6NjM3OX1dLCJuYW1lIjoicmVkaXMtc2VudGluZWwifQ==

  TYPESENSE_HOST: immich-typesense.media.svc.cluster.local
  TYPESENSE_DATA_DIR: /config
