---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DFLY_PASSWORD: "{{ .DFLY_PASSWORD }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        TYPESENSE_API_KEY: "{{ .TYPESENSE_API_KEY }}"
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .INIT_POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: DB_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d24a140e-3edc-42d8-8e9e-b14b00cc2027
        property: postgres_password
    - secretKey: INIT_POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d24a140e-3edc-42d8-8e9e-b14b00cc2027
        property: postgres_super_password
    - secretKey: TYPESENSE_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d24a140e-3edc-42d8-8e9e-b14b00cc2027
        property: typesense_api_key
    - secretKey: JWT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d24a140e-3edc-42d8-8e9e-b14b00cc2027
        property: jwt_secret
    - secretKey: DFLY_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d24a140e-3edc-42d8-8e9e-b14b00cc2027
        property: dragonfly_password
