---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
  data:
    - secretKey: DB_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d24a140e-3edc-42d8-8e9e-b14b00cc2027
        property: postgres_password
