---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/advplyr/audiobookshelf
      tag: 2.3.3
    env:
      TZ: "${TZ}"
      AUDIOBOOKSHELF_UID: 568
      AUDIOBOOKSHELF_GID: 568
      CONFIG_PATH: /config
      METADATA_PATH: /config/metadata
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: audiobookshelf.png
          gethomepage.dev/name: Audiobookshelf
          gethomepage.dev/group: Media
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          authentik.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:podcast
        hosts:
          - host: &host "audiobooks.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: longhorn
    persistence:
      media:
        enabled: true
        mountPath: /audiobooks
        path: ${SECRET_NFS_DATA}/audiobooks
        server: ${NAS_IP}
        type: nfs
      cache:
        enabled: true
        mountPath: /.npm
        type: emptyDir
    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        cpu: 16m
        memory: 118M
