---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 24T
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NAS_IP}
    path: ${SECRET_NFS_DATA}
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - relatime
    - nocto
    - noacl
    - nconnect=8
    - rsize=131072
    - wsize=131072
  claimRef:
    name: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  volumeName: media
  storageClassName: ""
  resources:
    requests:
      storage: 24T
