---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
spec:
  capacity:
    storage: 24T
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NAS_IP}
    path: ${SECRET_NFS_DATA}
  mountOptions:
    - hard
    - intr
    - nconnect=8
    - nfsvers=4.1
    - noacl
    - nocto
    - relatime
    - rsize=131072
    - tcp
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  volumeName: downloads
  storageClassName: ""
  resources:
    requests:
      storage: 24T
