---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tubearchivist-web
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: tubearchivist-elasticsearch
    - name: tubearchivist-redis
    - name: longhorn
      namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            setGateway: "true"
          securityContext:
            fsGroup: 1234
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            image:
              repository: bbilly1/tubearchivist
              tag: v0.5.0@sha256:d1ff4a9c1665571093e598be409a812d8709eb404d9b4ec1acdb7a4a2909f094
            env:
              TZ: "${TZ}"
              HOST_UID: 568
              HOST_GID: 1234
              ES_URL: http://tubearchivist-elasticsearch.media.svc.cluster.local:9200
              REDIS_CON: redis://tubearchivist-redis.media.svc.cluster.local:6379
              TA_HOST: &host tubearchivist.${SECRET_DOMAIN}
              TA_USERNAME: admin
              DISABLE_STATIC_AUTH: "true"
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 15m
                memory: 711M
            securityContext:
              capabilities:
                add:
                  - CHOWN

    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: tube-archivist.png
          gethomepage.dev/name: Tube Archivist
          gethomepage.dev/group: Media
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          # authentik.home.arpa/enabled: "true"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      cache:
        existingClaim: *app
      downloads:
        type: emptyDir
        sizeLimit: 10Gi
      youtube:
        type: nfs
        server: ${NAS_IP}
        path: ${SECRET_NFS_DATA}/youtube
