---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudnative-pg/ks.yaml
  - ./eck-operator/ks.yaml
  # - ./elasticsearch/ks.yaml
  - ./emqx/ks.yaml
  - ./redis/ks.yaml
