---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tubearchivist-web
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: tubearchivist-elasticsearch
    - name: tubearchivist-redis
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: bbilly1/tubearchivist
      tag: v0.3.6
    env:
      TZ: "${TZ}"
      HOST_UID: 568
      HOST_GID: 1234
      ES_URL: http://tubearchivist-elasticsearch.media.svc.cluster.local:9200
      REDIS_HOST: tubearchivist-redis.media.svc.cluster.local
      TA_HOST: &host tubearchivist.${SECRET_DOMAIN}
      TA_USERNAME: admin
      ENABLE_CAST: "true"
    envFrom:
      - secretRef:
          name: tubearchivist-secret
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          authentik.home.arpa/enabled: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: tube-archivist.png
          gethomepage.dev/name: Tube Archivist
          gethomepage.dev/group: Media
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      capabilities:
        add:
          - CHOWN
    volumeClaimTemplates:
      - name: config
        mountPath: /cache
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
    persistence:
      media:
        enabled: true
        mountPath: /youtube
        path: ${SECRET_NFS_DATA}/youtube
        server: ${NAS_IP}
        type: nfs
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 2000Mi
