---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tubearchivist-web
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: tubearchivist-elasticsearch
    - name: tubearchivist-redis
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        capabilities:
          add:
            - CHOWN

    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: bbilly1/tubearchivist
              tag: v0.4.4
            env:
              TZ: "${TZ}"
              HOST_UID: 568
              HOST_GID: 1234
              ES_URL: http://tubearchivist-elasticsearch.media.svc.cluster.local:9200
              REDIS_HOST: tubearchivist-redis.media.svc.cluster.local
              TA_HOST: &host tubearchivist.${SECRET_DOMAIN}
              TA_USERNAME: admin
              ENABLE_CAST: "true"
            envFrom:
              - secretRef:
                  name: tubearchivist-secret
            probes:
              liveness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 15m
                memory: 711M
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: longhorn
              globalMounts:
                - path: /cache

    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          # authentik.home.arpa/enabled: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: tube-archivist.png
          gethomepage.dev/name: Tube Archivist
          gethomepage.dev/group: Media
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        path: ${SECRET_NFS_DATA}/youtube
        server: ${NAS_IP}
        type: nfs
        globalMounts:
          - path: /youtube
