---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.1.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 30m
  values:
    upgrade:
      fromV2: true

    crds:
      install: true

    admissionController:
      replicas: 3
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
      serviceMonitor:
        enabled: true
        interval: 1m
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: kubernetes.io/hostname
          # whenUnsatisfiable: DoNotSchedule
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: kyverno

    grafana:
      enabled: true

    backgroundController:
      serviceMonitor:
        enabled: true
    cleanupController:
      serviceMonitor:
        enabled: true
    reportsController:
      serviceMonitor:
        enabled: true

    resources:
      requests:
        cpu: 247m
        memory: 443M
