---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: emqx
      version: 5.1.6
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    emqxConfig:
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${SECRET_EMQX_DEAFULT_PASSWORD}
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "emqx.${SECRET_DOMAIN}"
      externalIPs:
        - ${EMQX_METALLB_IP}
      externalTrafficPolicy: Local
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
          authentik.home.arpa/enabled: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: emqx.png
          gethomepage.dev/name: EMQX
          gethomepage.dev/group: Database
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        path: /
        pathType: Prefix
        hosts:
          - &host "emqx.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
    metrics:
      enabled: true
    persistence:
      enabled: true
      size: 1Gi
