---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: emqx
      app.kubernetes.io/instance: emqx
