---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset

    image:
      repository: lscr.io/linuxserver/calibre
      tag: 6.19.1

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    enableServiceLinks: false

    env:
      TZ: ${TZ}
      PUID: 568
      PGID: 568
      PASSWORD: ${SECRET_CALIBRE_PASSWORD}
      CACHE_DIR: /cache

    service:
      main:
        ports:
          http:
            port: &port 8080

    ingress:
      main:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: calibre.png
          gethomepage.dev/name: Calibre
          gethomepage.dev/group: Media
        ingressClassName: nginx
        hosts:
          - host: &host calibre.${SECRET_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        mountPath: /data
        path: ${SECRET_NFS_DATA}/ebooks
        server: ${NAS_IP}
        type: nfs
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache

    resources:
      requests:
        cpu: 50m
        memory: 470M

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
