---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset

    image:
      repository: lscr.io/linuxserver/calibre
      tag: 6.24.0

    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 1234
    #   fsGroup: 1234
    #   fsGroupChangePolicy: "OnRootMismatch"

    # enableServiceLinks: false

    env:
      TZ: "${TZ}"
      PUID: "568"
      PGID: "1234"
      # PASSWORD: "${SECRET_CALIBRE_PASSWORD}"
      # CACHE_DIR: /cache

    service:
      main:
        ports:
          http:
            port: &port 8080
      webserver:
        enabled: true
        ports:
          webserver:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081
        type: ClusterIP

    ingress:
      main:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: calibre.png
          gethomepage.dev/name: Calibre
          gethomepage.dev/group: Media
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          authentik.home.arpa/enabled: "true"
        ingressClassName: nginx
        hosts:
          - host: &host calibre.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        mountPath: /ebooks
        path: ${SECRET_NFS_DATA}/ebooks
        server: ${NAS_IP}
        type: nfs

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn

    # probes:
    #   liveness: &probes
    #     enabled: true
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /
    #         port: *port
    #       initialDelaySeconds: 0
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probes
    #   startup:
    #     enabled: false

    resources:
      requests:
        cpu: 15m
        memory: 411M
