---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.2.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.10.7
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/icon: authentik.png
        gethomepage.dev/name: Authentik
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/widget.type: authentik
        gethomepage.dev/widget.url: https://auth.${SECRET_DOMAIN}
        gethomepage.dev/widget.key: ${AUTHENTIK_TOKEN}
        external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hajimari.io/icon: simple-icons:webauthn
        hajimari.io/group: infrastructure
      hosts:
        - host: &host auth.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    geoip:
      enabled: false
    authentik:
      log_level: debug
      secret_key: ${AUTHENTIK_KEY}
      email:
        host: smtp.gmail.com
        port: 465
        username: ${SECRET_AUTHENTIK_EMAIL}
        password: "${SECRET_AUTHENTIK_SMTP_PASSWORD}"
        use_ssl: true
        from: id@${SECRET_DOMAIN}

      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s

      postgresql:
        host: '{{ .Release.Name }}-postgresql'
        name: authentik
        user: authentik
        password: ${SECRET_AUTHENTIK_POSTGRES_PASSWORD}
      redis:
        host: '{{ .Release.Name }}-redis-master'
        password: ${SECRET_AUTHENTIK_REDIS_PASSWORD}

    postgresql:
      enabled: true
      persistence:
        enabled: true
      postgresqlUsername: authentik
      postgresqlDatabase: authentik
      postgresqlPassword: ${SECRET_AUTHENTIK_POSTGRES_PASSWORD}
      image:
        tag: 15.2.0-debian-11-r26

    redis:
      enabled: true
      auth:
        enabled: true
        password: ${SECRET_AUTHENTIK_REDIS_PASSWORD}
      volumePermissions:
        enabled: true
