---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2023.4.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.4.1
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hajimari.io/icon: simple-icons:webauthn
        hajimari.io/group: infrastructure
      hosts:
        - host: &host authentik.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: *host
    geoip:
      enabled: false
    authentik:
      email:
        host: smtp.gmail.com
        port: 465
        username: ${SECRET_EMAIL}
        password: "${SECRET_AUTHENTIK_SMTP_PASSWORD}"
        use_ssl: true
        from: id@${SECRET_DOMAIN}
      secret_key: ${AUTHENTIK_KEY}
      log_level: debug

      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s

      postgresql:
        host: '{{ .Release.Name }}-postgresql'
        name: authentik
        user: authentik
        password: ${SECRET_AUTHENTIK_POSTGRES_PASSWORD}
      redis:
        host: '{{ .Release.Name }}-redis-master'
        password: ${SECRET_AUTHENTIK_REDIS_PASSWORD}

    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: authentik-postgresql-pvc

      postgresqlUsername: authentik
      postgresqlDatabase: authentik
      postgresqlPassword: ${SECRET_AUTHENTIK_POSTGRES_PASSWORD}

    redis:
      enabled: true
      auth:
        enabled: true
        password: ${SECRET_AUTHENTIK_REDIS_PASSWORD}
