---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.12.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  values:
    global:
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2024.12.5

    authentik:
      log_level: debug
      secret_key: ${AUTHENTIK_KEY}
      email:
        host: smtp.gmail.com
        port: 465
        username: ${SECRET_AUTHENTIK_EMAIL}
        password: "${SECRET_AUTHENTIK_SMTP_PASSWORD}"
        use_ssl: true
        from: id@${SECRET_DOMAIN}
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      postgresql:
        host: '{{ .Release.Name }}-postgresql'
        name: authentik
        user: authentik
        password: ${SECRET_AUTHENTIK_POSTGRES_PASSWORD}
      redis:
        host: '{{ .Release.Name }}-redis-master'
        password: ${SECRET_AUTHENTIK_REDIS_PASSWORD}

    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: authentik.png
          gethomepage.dev/name: Authentik
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/widget.type: authentik
          gethomepage.dev/widget.url: https://auth.${SECRET_DOMAIN}
          gethomepage.dev/widget.key: ${AUTHENTIK_TOKEN}
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/icon: simple-icons:webauthn
          hajimari.io/group: infrastructure
        hosts:
          - &host auth.${SECRET_DOMAIN}
        tls:
          - secretName: *host
            hosts:
              - *host
    geoip:
      enabled: false

    postgresql:
      enabled: true
      auth:
        username: authentik
        database: authentik
        password: ${SECRET_AUTHENTIK_POSTGRES_PASSWORD}
      primary:
        persistence:
          enabled: true

    redis:
      enabled: true
      auth:
        enabled: true
        password: ${SECRET_AUTHENTIK_REDIS_PASSWORD}
      volumePermissions:
        enabled: true
