---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/bazarr
              tag: 1.4.0
            env:
              TZ: "${TZ}"
              BAZARR__INSTANCE_NAME: Bazarr
              BAZARR__PORT: &port 80
              BAZARR__LOG_LEVEL: info
              BAZARR__API_KEY: ${BAZARR_TOKEN}
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
          subcleaner:
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.1.0
            imagePullPolicy: IfNotPresent
            args:
              - --repo=https://github.com/KBlixt/subcleaner.git
              - --branch=master
              - --depth=1
              - --wait=21600 # 6 hours
              - --root=/add-ons/subcleaner
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              globalMounts:
                - path: /config
              storageClass: longhorn

    service:
      main:
        ports:
          http:
            port: 6767

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: bazarr.png
          gethomepage.dev/name: Bazarr
          gethomepage.dev/group: Downloads
          gethomepage.dev/widget.type: bazarr
          gethomepage.dev/widget.url: http://bazarr.downloads:6767
          gethomepage.dev/widget.key: ${BAZARR_TOKEN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/bazarr/plex.css"></head>';
            sub_filter_once on;
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          authentik.home.arpa/enabled: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        existingClaim: downloads
        globalMounts:
          - path: /data
      add-ons:
        type: emptyDir
        globalMounts:
          - path: /add-ons
