---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.2.1
    env:
      TZ: "${TZ}"
      BAZARR__INSTANCE_NAME: Bazarr
      BAZARR__PORT: &port 80
      BAZARR__LOG_LEVEL: info
      BAZARR__API_KEY: ${BAZARR_TOKEN}
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: bazarr.png
          gethomepage.dev/name: Bazarr
          gethomepage.dev/group: Downloads
          gethomepage.dev/widget.type: bazarr
          gethomepage.dev/widget.url: http://bazarr.downloads:6767
          gethomepage.dev/widget.key: ${BAZARR_TOKEN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/bazarr/plex.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
    persistence:
      media:
        enabled: true
        existingClaim: downloads
        mountPath: /data
      add-ons:
        enabled: true
        type: emptyDir
        mountPath: /add-ons
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 1Gi
    sidecars:
      subcleaner:
        image: registry.k8s.io/git-sync/git-sync:v3.6.6
        imagePullPolicy: IfNotPresent
        args:
          - --repo=https://github.com/KBlixt/subcleaner.git
          - --branch=master
          - --depth=1
          - --wait=21600 # 6 hours
          - --root=/add-ons/subcleaner
        volumeMounts:
          - { name: add-ons, mountPath: /add-ons }
