apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:qnYytKMlmNZfw/62TUfTE2auyIjDmOul,iv:vJZayvexoIMVWtDg/1QIAG0Z28knz4J+eAXRwLbIYlY=,tag:ArGWJd6QMgtE0uWPRIfjhw==,type:str]
    api-key: ENC[AES256_GCM,data:XdcddaVpTAonxtPqzMctwMvQd29X0876nPwjGhAEPjDzQaJLCw==,iv:JNQv+nVmbPjqF80F1EjC7vsijIA9lbDmhm4t1NxhNUo=,tag:ldw2PNbVdZ95o1yZPp/hqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNnEvMmZtQ2VlQ3FGcEZU
            V0E4N1NMM1AzNGdDS3NPaitmL3VBTngyT2g0CnF2TjVJSHE2Y2dZK3ZsRzIwYjNn
            Rit4aXdndFJKQmtrRnM1NEJNeTVwb1EKLS0tIFhwYzlYaEQwNjBWYTNmRzluYkYv
            VW9vOUVlS0dYdFFOdTNLMzVuRzhUcjAKZtBmgtpmFDpBsEQfZVR4s4lEaEQILD0C
            KIAFoNxIqoOWqpn/qWgiSAoPVjnCyZmanhNIE9HOQTD7cPxf0eSBaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T09:03:22Z"
    mac: ENC[AES256_GCM,data:FhvtLQW1etzcUY+R9roWirosOaLlnJTluV/CIXSl6ayJkgyS92633T3rihdX3jvsAt8IA9XahBLzMqS46VYRbTsYmW3L8JO5i7XHjIkoYJ6wgxzE246+WpFySahvqel+xLCbFGv0pLafH+APSAY6QmndCjyPOu1IVjjFuXYEyIs=,iv:wy1D9le3rcdjP+RRtKwSQPGh49r6pqmuGo7qKOOzoEA=,tag:9CO3SUiyGZYdiOFCDDjNqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
