---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./hajimari/ks.yaml
  - ./homepage/ks.yaml
  - ./misc-ingress/ks.yaml
  - ./theme-park/ks.yaml
