---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
      reclaimPolicy: Delete
      defaultClassReplicaCount: 3
    ingress:
      enabled: true
      ingressClassName: nginx
      host: &host "longhorn.${SECRET_DOMAIN}"
      tls: true
      tlsSecret: *host
      path: /
      annotations:
        hajimari.io/enable: "true"
