---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: autoscan-configmap
    files:
      - ./configs/config.yml
  - name: autoscan-plex-token
    files:
      - ./configs/plex.token
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: autoscan
      app.kubernetes.io/instance: autoscan
