---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}"
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
  data:
    - secretKey: POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 235c0297-6cd4-490f-aff3-b0d301388323
        property: postgres_password
