---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app immich-postgres
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      postgres:
        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload: &configmap immich-configmap
          secret.reloader.stakater.com/reload: &secret immich-secret
        containers:
          app:
            image:
              repository: tensorchord/pgvecto-rs
              tag: pg16-v0.2.1
            env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: INIT_POSTGRES_SUPER_PASS
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: *configmap
                    key: INIT_POSTGRES_USER
            envFrom:
              - secretRef:
                  name: *secret
              - configMapRef:
                  name: *configmap
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 249M

    service:
      app:
        controller: postgres
        ports:
          postgres:
            port: 5432

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /var/lib/postgresql/data
            subPath: postgresql

      initdb:
        type: configMap
        name: immich-postgres-extensions
        globalMounts:
          - path: /docker-entrypoint-initdb.d/create-extensions.sql
            subPath: create-extensions.sql
