---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        capabilities:
          add:
            - CHOWN
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/haveagitgat/tdarr_acc
              tag: 2.00.20.1
            env:
              TZ: "${TZ}"
              PUID: "568"
              PGID: "568"
              ffmpegPath: "/usr/local/bin/ffmpeg"
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
        statefulset:
          volumeClaimTemplates:
            - name: server
              mountPath: /app/server
              accessMode: "ReadWriteOnce"
              size: 5Gi
              storageClass: longhorn
            - name: configs
              mountPath: /app/configs
              accessMode: "ReadWriteOnce"
              size: 1Gi
              storageClass: longhorn

    service:
      main:
        type: LoadBalancer
        enabled: true
        externalTrafficPolicy: Local
        loadBalancerIP: "${TDARR_METALLB_IP}"
        ports:
          http:
            enabled: true
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: tdarr.png
          gethomepage.dev/name: Tdarr
          gethomepage.dev/group: Downloads
          gethomepage.dev/widget.type: tdarr
          gethomepage.dev/widget.url: http://tdarr.downloads.svc.cluster.local:8265
          hajimari.io/icon: clarity:media-changer-solid
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          authentik.home.arpa/enabled: "true"
        hosts:
          - host: &host tdarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        enabled: true
        existingClaim: downloads
        globalMounts:
          - path: /data
