---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-configs
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  volumeName: tdarr-configs
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  volumeName: tdarr-cache
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
