---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-configs
spec:
  storageClassName: longhorn
  claimRef:
    name: tdarr-configs
    namespace: downloads

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-cache
spec:
  storageClassName: longhorn
  claimRef:
    name: tdarr-cache
    namespace: downloads

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-configs
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
