apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:r4JhQHSYKTxjTwx+BYke2ydmZpSVxfgLyt0VCk7ZrdWOJXdX3da1cnjOqiuQfiRR2EaVto1S+Zp3aWiJ,iv:QDcFf2vqQP8+zsSE6bvq7NwdpZHU5c6jtqlt7JEJBKA=,tag:75qVqV4yUJB7Gkf46M+i5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkOHJYY1dsVWdYYzA5Rm1H
            QXExNktNWUFOQ1ZFQ1Q2YUZOaG9ZTnY0WHdJCjFBZGxva3NkeVM1L3NGWW1GK3pR
            VEtITGtpUitZblNBZXhYaWRybGQ5bXcKLS0tIHRBLzR0MFpnOVk3SFlWenRYZVpI
            dDJRV01IV0k1ODRjdzcyQ3ZaOUJKcVkKLX83TqIl0ts4ZynrZVnIymLfIPMdYTHR
            fUyROPkQbwAAR8zgvHHRzPf8vN3/0zRzlggjQUnccF9K4hMOnZEAdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T13:11:53Z"
    mac: ENC[AES256_GCM,data:8bdea+kA9dUkauTgLpaBxv8G0mpR4+/4h1DY6x6CYwx0gBsK90Uy17IKqaCrXK7801E4aGZmRcy97WOq7Edou80HEugZnx8293SmNUi65u9Wj1CpZ2sKuCEg2C3+TqprKU9oKpbmiiLavP+CzUf8JMu8P0StdHgYHVDHr5Oo+hI=,iv:rTDY5rxOKaWaIRI7hsheir11HgEKkoU6X3EV/Gy9kLo=,tag:lKuVHon5gRaJ7u37IDAvXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
