apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:LKKn27TFc5Ifa4AchYVM0lAjIVgx4BpoO+5hvLwvG5EppKUlCq0IlPPTAXXmkuLoDvNwhTypsjGCPTbD,iv:sS6P0BuNxX6zYAZ2XxMwoV4f1fP9SZTb2m2w35jhT1U=,tag:NxMus/U05+L1x+QKYfswsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY2Nid0YxZ2hCT1NZdzc4
            VGx0L0EvcmYvTm05YVBvL1dEemxwOEJVRkF3CjFydzNnMGs5ZW5oYnUwWjI0ZGpj
            YWFCc0Z3ejJpMUZNNUh3T3VDZkFaQUkKLS0tIFR6TWg1YjJlQ0F4RmpZQ3Z1RTA4
            UmpNOUF1aGNYRTZxTWNmRHNQbmpBa1EKuREHjwUvv66mEQmCmGQV/sGjcITYSHL3
            H0pt1gCsXpip95IUB1mABoySlNMqbTcnuvDg9NdCKWpqjRL/6tYAkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T15:44:22Z"
    mac: ENC[AES256_GCM,data:+DFF1ApPeYksa9WAJgkRpok43DDl1LvJXFZd3fNsbDErOaBNzC0BRSxPzXhao1vrWFElUhMQl7VOaVspHC8mWJgKVG51G25OuP1TYXjzehwU9Jx9MTaCLKqg4BNNoqabOUjpPkTPqHFF1VSd+oBAgXtejzRpSSe4ln/P7U+dcls=,iv:44vT6crUmiWiIFM8YrSZMdDhNOwm3Bxsa9C0t4FmIrA=,tag:IxqYXzN+nW0aXsRgJHm0Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
