---
# ref: https://github.com/onedr0p/home-ops/blob/main/kubernetes/apps/default/frigate/app/config/config.yaml

mqtt:
  enabled: false

go2rtc:
  streams:
    frigate_garage_lq: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.180:554/cam/realmonitor?channel=1&subtype=1
    frigate_garage_hq: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.180:554/cam/realmonitor?channel=1&subtype=0

cameras:
  garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_garage_lq
          roles:
            - detect
        - path: rtsp://localhost:8554/frigate_garage_hq
          roles:
            - record
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 10

detectors:
  cpu1:
    type: cpu
    num_threads: 3
    model:
      path: /cpu_model.tflite
  # coral1:
  #   type: edgetpu
  #   device: pci:0
  # coral2:
  #   type: edgetpu
  #   device: pci:1

record:
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 7

birdseye:
  enabled: true
  mode: continuous

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 5
