---
# ref: https://github.com/onedr0p/home-ops/blob/main/kubernetes/apps/default/frigate/app/config/config.yaml

mqtt:
  enabled: false

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://"{SECRET_IMOU_USERNAME}":"{SECRET_IMOU_CAM1_PASSWORD}"@192.168.1.101:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
    detect:
      enabled: false
