---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            type: statefulset
            annotations:
              reloader.stakater.com/auto: "true"
            image:
              repository: ghcr.io/onedr0p/radarr-develop
              tag: 5.2.3.8303
            env:
              TZ: "${TZ}"
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 80
              RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
              RADARR__LOG_LEVEL: info
              RADARR__API_KEY: ${RADARR_TOKEN}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: radarr.png
          gethomepage.dev/name: Radarr
          gethomepage.dev/group: Downloads
          gethomepage.dev/widget.type: radarr
          gethomepage.dev/widget.url: http://radarr.downloads
          hajimari.io/icon: movie-check
          gethomepage.dev/widget.key: ${RADARR_TOKEN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          authentik.home.arpa/enabled: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        enabled: true
        size: 2Gi
        globalMounts:
          path: /config
        storageClass: longhorn

      media:
        enabled: true
        existingClaim: downloads
        globalMounts:
          path: /data

    #   add-ons:
    #     enabled: true
    #     type: emptyDir
    #     mountPath: /add-ons
    # sidecars:
    #   tdarr-inform:
    #     image: registry.k8s.io/git-sync/git-sync:v3.6.7
    #     imagePullPolicy: IfNotPresent
    #     args:
    #       - --repo=https://github.com/deathbybandaid/tdarr_inform.git
    #       - --branch=master
    #       - --depth=1
    #       - --wait=21600 # 6 hours
    #       - --root=/add-ons/tdarr-inform
    #     volumeMounts:
    #       - { name: add-ons, mountPath: /add-ons }
