---
server:
  host: 0.0.0.0
  port: 7441
  apiToken: ${OMEGABRR_TOKEN}
schedule: "0 */8 * * *"
clients:
  autobrr:
    host: http://autobrr.downloads.svc.cluster.local:7474
    apikey: ${AUTOBRR_TOKEN}

  arr:
    - name: radarr
      type: radarr
      host: http://radarr.downloads.svc.cluster.local
      apikey: ${RADARR_TOKEN}
      filters:
        - 1

    - name: sonarr
      type: sonarr
      host: http://sonarr.downloads.svc.cluster.local
      apikey: ${SONARR_TOKEN}
      filters:
        - 2
      excludeAlternateTitles: true
