---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}"
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        TA_PASSWORD: "{{ .TA_PASSWORD }}"
        ELASTIC_PASSWORD: "{{ .ELASTIC_PASSWORD }}"
  data:
    - secretKey: TA_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1fd55c03-ec57-488f-92da-b0dc0092e083
        property: tubearchivist_password
    - secretKey: ELASTIC_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1fd55c03-ec57-488f-92da-b0dc0092e083
        property: elastic_password
