---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-server
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: immich-typesense
  values:
    defaultPodOptions:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app

    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          configmap.reloader.stakater.com/reload: &configmap immich-configmap
          secret.reloader.stakater.com/reload: &secret immich-secret

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 15.5
            envFrom:
              - secretRef:
                  name: immich-secret
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.89.0
            command: /bin/sh
            args:
              - ./start-server.sh
            envFrom:
              - configMapRef:
                  name: *configmap
              - secretRef:
                  name: *secret
            resources:
              requests:
                cpu: 100m
                memory: 250Mi

    service:
      main:
        ports:
          http:
            port: 3001

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: immich.png
          gethomepage.dev/name: Immich
          gethomepage.dev/group: Home
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hajimari.io/appName: Immich
          hajimari.io/icon: heroicons:photo
        hosts:
          - host: &host photos.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      library:
        enabled: true
        existingClaim: immich-nfs
        namespace: home
        globalMounts:
          - path: /usr/src/app/upload
