---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.32.1.6999-91e1e2e2c@sha256:fa9bbdbd8a73d110c703839619b9e1cc13524187b00662955235c02e07cef50c
    env:
      TZ: "${TZ}"
    service:
      main:
        type: LoadBalancer
        # externalTrafficPolicy: Local
        # loadBalancerIP: "${SVC_PLEX_ADDR}"
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: plex.png
          gethomepage.dev/name: Plex Kubernetes
          gethomepage.dev/group: Media
          gethomepage.dev/widget.type: plex
          gethomepage.dev/widget.url: http://plex.media:32400
          gethomepage.dev/widget.key: ${PLEX_TOKEN}
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:plex
          hajimari.io/enable: "false"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      # supplementalGroups:
        # - 44
        # - 109
        # - 65539

    # nodeSelector:
    #   intel.feature.node.kubernetes.io/gpu: "true"

    resources:
      requests:
        cpu: 100m
        # gpu.intel.com/i915: 1
        memory: 4282M
      limits:
        # gpu.intel.com/i915: 1
        memory: 8G
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 70Gi
        storageClass: longhorn
    persistence:
      media:
        enabled: true
        existingClaim: media
        mountPath: /data
