apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: media
spec:
  containers:
    - name: debug-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /mnt/debug
          name: debug-volume
  volumes:
    - name: debug-volume
      persistentVolumeClaim:
        claimName: tubearchivist-web
