apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migrate-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 70Gi
  storageClassName: longhorn
