---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.72
    ports:
      - name: http
        port: 32400

---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 32400
      targetPort: 32400

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    hajimari.io/icon: video-input-antenna
  name: plex
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: &host "plex.${SECRET_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: plex
                port:
                  number: 32400
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
