---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: downloads-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.11.1@sha256:0617304f085bc98529f0c5cd0c40c63bb019380a026a277c812bd13f78b4bc5d
    DNS: 172.16.1.1
    addons:
      netshoot:
        enabled: true
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.39.1@sha256:6a8058e626763cbf735ac2f78c774dbb24fec2490bd9d9f7d67e22592cb4a991
        env:
          - name: VPN_SERVICE_PROVIDER
            value: custom
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: VPN_ENDPOINT_IP
            value: 143.244.47.38
          - name: VPN_ENDPOINT_PORT
            value: 51820
          - name: DNS_ADDRESS
            value: 172.111.139.2
          - name: LOG_LEVEL
            value: debug
        envFrom:
          - secretRef:
              name: pod-gateway-secret
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                - port: 51820
                  protocol: UDP
            - to:
                - namespaceSelector: {}
    podAnnotations:
      configmap.reloader.stakater.com/reload: pod-gateway-downloads
      secret.reloader.stakater.com/reload: downloads-gateway-vpnconfig

    publicPorts:
      - IP: 10
        hostname: qbittorrent
        ports:
          - port: ${SECRET_VPN_FORWARDED_PORT_1}
            type: udp
          - port: ${SECRET_VPN_FORWARDED_PORT_1}
            type: tcp

    routed_namespaces:
      - downloads
      - media

    settings:
      VPN_INTERFACE: "wg0"
      VXLAN_ID: "43"
      VXLAN_IP_NETWORK: "172.16.1"
      VPN_BLOCK_OTHER_TRAFFIC: "true"
      VPN_TRAFFIC_PORT: "51820"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 192.168.0.0/16"
      VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0
