---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpn
resources:
  - ./helmrelease.yaml
  # - ./network-policy.yaml
  - ./secret.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: pod-gateway
      app.kubernetes.io/instance: downloads-gateway
