apiVersion: v1
kind: Secret
metadata:
    name: pod-gateway-secret
    namespace: vpn
stringData:
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:MsXw7dYkJFJV42C4wnaPfkGeU2ojO8v9UVmXq5lhyn3mwRPcOW9UQlurEK0=,iv:U4oNheOS247/QMDw7/I2ISpjpBXVfQqJyLYBSYiEQXA=,tag:+Z8GW6GUu8D5GNpeN+dWiw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:VOPMR7oJNJqcZSvSEOw/McEe2XgKk2q7E05iiw433Emi5t8OXzFfxuw6QGo=,iv:+p9yGZyVBUD0mOYaPF3NCISA9wwFvmTc7j22BlOABiw=,tag:w2VlzA54cOtShchNLG5+Ug==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:rMZqc8DP0b4VIKJgx455,iv:3CSwhf9wCAAxx8mYF6kHyn0JzHaGwicJmUFruRTX1FY=,tag:8sdkRnY1xpHRwvTxJTi/nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVFVuZE9MOVhYZndFNXM3
            YnlEMkIvUHhMMUpFd3p4SlpsZ0hRcXpSSkNNCkhqdG5vUm1RUnplVTEwZmRRSExv
            YVgxWDVQSVlKMlJPdTFPdnlEaDFIZHMKLS0tIEtpZk0xT2Qzdjl3RFF5K2tpTE0x
            YTBXdmpEUktIQ3BHejZHRmVSWnJkUU0KnU6EJa+6slNHZUxetxmV31wtwCfYwmLl
            M8jApn/5jewliIyjV+VmuDmz7S3xI7cv43FQwOKvnZjSOcSSkHzMBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T18:37:19Z"
    mac: ENC[AES256_GCM,data:UInSlLhF97D7OK75FUgpqCZpnqASuf8ytM4wSx17Dw1gNTksm+DVI9Q+jsArfWi+XEcAi8nJp6NZOz4dGdXbI0MkgGc7Pl8OlfQolsibFnmnvWq3yG1vC4dN5Ob2kkC5XvqHnmzaAZDBiHkwmneDfCQZplyl6GN3Kw1HhXDsBSs=,iv:I6yj38pZrOAkjyE5aopgeQAm73hAaf8Ngau6LIBU6YE=,tag:PM3qdKQsTgZg1XKR3fN2Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
