apiVersion: v1
kind: Secret
metadata:
    name: pod-gateway-secret
    namespace: vpn
stringData:
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:+tJs9x4tnppUOP6d0NXw/WS1rMhtMuBxFzl8DpuuB6/Epx9QLWxE7nDn6l4=,iv:QNi1oAYqbZ1aAHakfJNcDIsOUNev2nlA5TRyzXOPwKY=,tag:8vIeejTdph4+UIfoYx4ZcQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:BTTstUT0BdjEAWDBuuC3NitqE6J/xs6COKGq9eVaLaLpnDZpgfMFkWhjmlc=,iv:SNWuADZKVss9ukiWMygtI3K30p9Q5d9+fO9T/CRouYg=,tag:GEMYU1+5Olm7ueemy6DzEg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:9ygJO0Rpt+EnFFk2jQ==,iv:IsHpvJ2rcd1w9E6m3kT6rBCrYXIIp1ia/V41bhT1eVo=,tag:wrkd9UGT6+xxsbXRxaZaAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVFVuZE9MOVhYZndFNXM3
            YnlEMkIvUHhMMUpFd3p4SlpsZ0hRcXpSSkNNCkhqdG5vUm1RUnplVTEwZmRRSExv
            YVgxWDVQSVlKMlJPdTFPdnlEaDFIZHMKLS0tIEtpZk0xT2Qzdjl3RFF5K2tpTE0x
            YTBXdmpEUktIQ3BHejZHRmVSWnJkUU0KnU6EJa+6slNHZUxetxmV31wtwCfYwmLl
            M8jApn/5jewliIyjV+VmuDmz7S3xI7cv43FQwOKvnZjSOcSSkHzMBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T14:51:12Z"
    mac: ENC[AES256_GCM,data:aZJr8NAYcsZafaD67jDWj9ECwzyR47+gJKWZurCOPJOmJ+A8oVsgACTuCGDQXpM8BOykoBlcTFx5CSZgQDFWGluAMFqpVDqvh45A0B4t190/z6WouBvBfJ/8CIwqwFNBnaTRlNsqY1TpLcIYP50VQBUJhT9lE1Moc/nVNpSG+/o=,iv:75xsc40y8h7b3+svj9Tm7oG+JJZX0akIqI/ADR5NAoo=,tag:REARrgu/VFhoMjBoz6PSPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
