apiVersion: v1
kind: Secret
metadata:
    name: pod-gateway-secret
    namespace: vpn
stringData:
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:Pt3x33FZothKq/KiIyCWfX8bEX6tjkzff/gclqtU2Et70ZeBgOUujketdLY=,iv:dN654aSucSyripYujafmPQk3lLI+WrO1QHsAB20r82M=,tag:gElVXLo934m8M1h/kAOdqg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:kIycx1IlLycpZQe97SFEUpSpGDjZ+Cc2V0bkH3jZs4CgYi9YMA4milU3c7A=,iv:m1ls1JzAv37Q+VMOMEqf/UjfgalviBtgC8VMUjBfQGE=,tag:KHP4fmJT5C3Iaidvv3sdvA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:zHidpogqZnB8YtrTyUZF,iv:2vQH9XK8WCnyX6dwaJiA+xu4ucuVQtL5ysgn7wXmT9g=,tag:6Qqa28iudAOiBOxGvOC1Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVFVuZE9MOVhYZndFNXM3
            YnlEMkIvUHhMMUpFd3p4SlpsZ0hRcXpSSkNNCkhqdG5vUm1RUnplVTEwZmRRSExv
            YVgxWDVQSVlKMlJPdTFPdnlEaDFIZHMKLS0tIEtpZk0xT2Qzdjl3RFF5K2tpTE0x
            YTBXdmpEUktIQ3BHejZHRmVSWnJkUU0KnU6EJa+6slNHZUxetxmV31wtwCfYwmLl
            M8jApn/5jewliIyjV+VmuDmz7S3xI7cv43FQwOKvnZjSOcSSkHzMBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-24T09:05:24Z"
    mac: ENC[AES256_GCM,data:3VJA9HCHx1Q7Ft8K/UXV7ccFyY3JsfbmWstenBH9TouINgRHnwgysPyrEfAiXP7TSgoU7/zN/gWYpw9yrjWf8iLCZ4IdHkAsyQxm572MPhEzRi3BhtLRqmhgclMs05fxgEc+yEYcB+lU+Ovl8wUI47iY4H0WUNgXgURIrpzARXY=,iv:YLBH4CaCvanaymJWRnxBhJ5Opr+iiaGkMfyzDAN9pYs=,tag:i13fr+HsGJhgb7j8ej9+XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
