---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skkweb
  namespace: external
  annotations:
    external-dns.home.arpa/enabled: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: &host "skkweb.${SECRET_DOMAIN}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: skkweb
                port:
                  number: 80
  tls:
    - hosts:
        - *host

---
apiVersion: v1
kind: Endpoints
metadata:
  name: skkweb
  namespace: external
subsets:
  - addresses:
      - ip: 192.168.1.73
    ports:
      - name: http
        port: 80
        protocol: TCP
