apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:VR3rVA/Hg0I=,iv:AMOMisWAfkM82ucgjOW0wFrwfkmPGpHqFRePx5sMxIY=,tag:edxE36q0mgF2j9EjVzjdFg==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:w0nYv1WXtT0NhdYgNFWMxmBdWYRMzQgRQr0=,iv:4/cIMcLcs2ussb2G6Mr7jtuy+YTU8TjN/Ih+XWSPXhY=,tag:1wO+cbxxi2/35jRmGGPkRQ==,type:str]
    AWS_ACCESS_KEY: ""
    AWS_SECRET_ACCESS_KEY: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNE5ZbTVWU2N5V3ZGanpk
            cE1mTDFEMDUzdkVsT2Y1MThxODRydklRUFdNCk8weXZleHQ2WEtrOTV6NzNYT05L
            dFhuSks3cGJMZHJkTmhxK0FpVTU4eU0KLS0tIFM5K292MFlpc05idGIvQUNnYUhl
            aEkvZ09aYUlrTHRtM1F2aUxuREtjZ28KLoF8lNMlatujX/0R98MhlNfdkx7YCuLK
            PpT4lnpBeeAuq/cMPqL38r2VJBp/1ZNl2oUoGimmVmtu8bz2oRM4/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T18:01:29Z"
    mac: ENC[AES256_GCM,data:1+MSFnfT/acEVJQGnGAboh4ocO+q7Nb+ENOTJHhCbTye+VDLiV+UvIZFHla4cIIqRwzSvum3QRndRhI0m5bjRGvMnUSvJRXq6YbkUj+KbMfv0YWyE6Wl+m1NjdiMMo1+SiQm9TAGVeXaYuSIk5GirTduAz9YIJmZ14Ixh3gCNo0=,iv:P9nhSXscRIYkD8Ft8CKIR9ohvE7zFOhnxtouv8xYh6c=,tag:0vmUwCZMrNy2eS7KgBxOsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
