apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:VR3rVA/Hg0I=,iv:AMOMisWAfkM82ucgjOW0wFrwfkmPGpHqFRePx5sMxIY=,tag:edxE36q0mgF2j9EjVzjdFg==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ncMG7LcMvxOqxpNgb4wbr8cowNwp5eDI,iv:9zp8YV1YY816B8QL/DQBTMEuv4ih2PJyc0AVAtRpQ9M=,tag:HmWQkn5TFZ6JbBLS9P4HVg==,type:str]
    AWS_ACCESS_KEY: ""
    AWS_SECRET_ACCESS_KEY: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNE5ZbTVWU2N5V3ZGanpk
            cE1mTDFEMDUzdkVsT2Y1MThxODRydklRUFdNCk8weXZleHQ2WEtrOTV6NzNYT05L
            dFhuSks3cGJMZHJkTmhxK0FpVTU4eU0KLS0tIFM5K292MFlpc05idGIvQUNnYUhl
            aEkvZ09aYUlrTHRtM1F2aUxuREtjZ28KLoF8lNMlatujX/0R98MhlNfdkx7YCuLK
            PpT4lnpBeeAuq/cMPqL38r2VJBp/1ZNl2oUoGimmVmtu8bz2oRM4/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T18:25:55Z"
    mac: ENC[AES256_GCM,data:JF/4jffpqpaOG0nL/+8sDNQMBCBelMoN4tBSrisuqvIH6ctcu3W5QDn+Elw29xhGlp+ouRSQ+NWrN95J+NaOtWAWMdcwXvZ1jv9jNhoJF5BkpCY1Yo7X+qwQS7btrUN1H1jQkveX9Swcky+shG4LEBZ2UTGFAjTWZ0RgRpfqEK0=,iv:0ACV84OiF4cadZ71ocSrInHqCZSYhLTriFOS7+H5tbk=,tag:uSyIhwcR5gb3qAGk+Gz7dA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
