---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: qbittorrent2
      app.kubernetes.io/instance: qbittorrent2
