apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent2-secret
    namespace: vpn
stringData:
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:sJdj9/J5qPS8P8yDcCIb4xefhyVU6mwak3LgxF9T5n5X+TQFxEgxWRIBX5U=,iv:XILmjOP5KtvP+hBbgc5viB/0FHDZkNHbWIFzviUXEvU=,tag:RsXHsclDVG+v7ulhnHuZ1Q==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:boe1MTn+HRCCMSJQkdFDkuorsJctXQpai0zq9kAd33sNRry6xXNkr9NVZQE=,iv:oF1E8vMm6Ltg/VxNu88yI8t1kjeGmtsH9MMypo5kFhk=,tag:gtNl+/S0RcuLR2QkvhYUHQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:kMeZE5WnWyVsuayMR+Nx,iv:uhakxQKQ+9eULm34DLUtgw10rRzEEqvZ9UHOc8YqCZU=,tag:5sz+EPnjtJOe7h5Yl6Xilw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVFVuZE9MOVhYZndFNXM3
            YnlEMkIvUHhMMUpFd3p4SlpsZ0hRcXpSSkNNCkhqdG5vUm1RUnplVTEwZmRRSExv
            YVgxWDVQSVlKMlJPdTFPdnlEaDFIZHMKLS0tIEtpZk0xT2Qzdjl3RFF5K2tpTE0x
            YTBXdmpEUktIQ3BHejZHRmVSWnJkUU0KnU6EJa+6slNHZUxetxmV31wtwCfYwmLl
            M8jApn/5jewliIyjV+VmuDmz7S3xI7cv43FQwOKvnZjSOcSSkHzMBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-03T09:41:11Z"
    mac: ENC[AES256_GCM,data:dOzltipWrWv38PRTfZsdaJa776p7PgZeVQGf8QPRtRE/SFN5xS2qJb7LcCNzwAcj9F8GvUBnPPXHcTzaF3CBoVVDgVDyu9LH61ecLvoWgue0B7fplJilzVD3uPoirp2oYdfdzljSPsJtZe+2z7BHii2SoDXToyk3QFCB/swcHe4=,iv:hFxZWgYHml3OCInMBLIuih5RhIiPwr/xXjq1aW7abgA=,tag:aVKo5NK0FUwi2Y0W3Bup0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
