---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: longhorn
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 3
  install:
    replace: true
    crds: Create
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  uninstall:
    keepHistory: false
  values:
    upgradeVersionCheck: false
    longhornUI:
      replicas: 1
    monitoring:
      enabled: true
      createPrometheusRules: true
    defaultSettings:
      deleting-confirmation-flag: true
