---
collections:
  - name: community.general
    version: 10.7.3
  - name: community.sops
    version: 1.9.3
  - name: ansible.posix
    version: 1.6.2
  - name: ansible.utils
    version: 6.0.0
  - name: kubernetes.core
    version: 5.4.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.5.0
