---
collections:
  - name: community.general
    version: 8.6.5
  - name: community.sops
    version: 1.9.0
  - name: ansible.posix
    version: 1.6.0
  - name: ansible.utils
    version: 5.1.2
  - name: kubernetes.core
    version: 3.2.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.4
