apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1MS+VnxkulkEg5MuQktWFlooSs/4+Sa8DBOZn4wszQMp8JXK,iv:eYve7kOLKLApaxR5YG1F6wa4h9apCGYS77hhwuyhhZo=,tag:Cu5aQB4EYRCGF73Cb13Thg==,type:str]
    credentials.json: ENC[AES256_GCM,data:xYSXENf0mdua08Utan0HfFwDrmRLAdZv+qaLNCtYRY1tXAEfLsYD9/Tbxd+inDWKImifxOqvCMaLxsXxS8k4lUtAWPYyiJloy0n0mAF36VJNWOWIQUcWhvIAr4sq9fGCQOjWcQlEmsrWqJFGAOUFjIBLJF8FhAAsD4D8FBJPw73RwImZf2FEwDfBb5Tu4qfUNDclMv1hRpJLB8lsLo9iBiFbP/+PIKlJ0Qy0n0EDaw==,iv:5SuhVZB1twhF+y8LKt5HfD09xGUNHYNlVvPRpxXRp28=,tag:FeI8zi2bLc5Fgqr6pGERAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1362xs7tspa2e05ma8lkzrw0x0rrw7f5nrl5jegl79tv2ht7hl3vsl4y82j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT0NtSkVLTytsckZ6V1ov
            bFZyTTVJYytramYyV1k3UCtnWnhCMG1TMmc4ClYyQnZrcm9YUFpFYktMZzJRQWp3
            SU9laS91bUx3SHRHRWlHUy94L0gzVUUKLS0tIGxMYTJPQnpBRDJybE9NaWpwTW5Y
            TFJjSFVmNnRWb3BSRndtZyt4VmxBY1UKKOesa8Dgx6gt7X/wDM20QDbSf4YQf/6X
            hHsLF0KuXbL/UqcduGKUQAWgUyvQ8abdJCSszGCHF1Td0Twnm4GsDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T09:03:22Z"
    mac: ENC[AES256_GCM,data:ipQ8kQSFXBAnBVw37H7GmXKMUf57KWO2uuAsamBA6ZiflWP6nYCz2kZnlh9Dqof69NrOsHLWOHYeYNWezdlW3TXQsTLMc7vw36CUL//aw0R9yPecfoRsygTYdjngV/2xZdXYwJRStO1R0fcE9CxxIup0qhFMfhLadhrwv0XIibE=,iv:ogexJlg3PP9kcjNOZ1zEgmvVXx/7YF+UnXuHSyr4hp4=,tag:PP9NB37p78y+9cjzv5Pxtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
