---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    reloader.stakater.com/match: "true"
data:
  settings.yaml: |
    ---
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Media:
        style: row
        columns: 3
        icon: mdi-play-circle
      Infrastructure:
        style: row
        columns: 3
        icon: mdi-harddisk
      Home:
        style: column
        rows: 2
        icon: mdi-home-analytics
      Monitoring:
        style: column
        rows: 2
        icon: mdi-chart-line
      Minecraft:
        style: row
        columns: 3
        icon: mdi-minecraft
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
    providers:
      longhorn:
        url: http://longhorn-frontend.storage
  widgets.yaml: |
    # - resources:
    #     backend: kubernetes
    #     cpu: true
    #     expanded: true
    #     memory: truehttps://github.com/walkxcode/dashboard-icons/blob/main/png/homepage.png?raw=true
    - logo:
        icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/lds-transparent.png
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Howdy Hey!"
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - openmeteo:
        label: Home
        latitude: ${LATITUDE}
        longitude: ${LONGITUDE}
        units: metric
        cache: 5
    - longhorn:
        expanded: false
        total: true
        labels: true
        nodes: false
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
  services.yaml: |
    ---
    # - Media:
    #     - Plex Docker:
    #         href: https://plex-docker.${SECRET_DOMAIN}
    #         icon: plex.png
    #         widget:
    #           type: plex
    #           url: http://${NAS_IP}:32400
    #           key: ${PLEX_TOKEN}
    #     - Tautulli Docker:
    #         href: https://tautulli-docker.${SECRET_DOMAIN}
    #         icon: tautulli.png
    #         widget:
    #           type: tautulli
    #           url: http://${NAS_IP}:8181
    #           key: ${TAUTULLI_TOKEN}
    #     - Tdarr:
    #         href: https://tdarr.${SECRET_DOMAIN}
    #         icon: tdarr.png
    #         widget:
    #           type: tdarr
    #           url: http://${NAS_IP}:8265
    - Infrastructure:
        # - Unraid:
        #     href: https://nas.${SECRET_DOMAIN}
        #     icon: unraid.png
        #     description: Unraid WebUI
        # - Unifi:
        #     href: https://unifi.ui.com
        #     icon: unifi.png
        #     description: Unifi Dashboard
        #     widget:
        #       type: unifi
        #       url: https://192.168.1.1:443
        #       username: ${UNIFI_USERNAME}
        #       password: ${UNIFI_PASSWORD}
        - PiHole:
            href: http://${PIHOLE_URL}
            icon: pi-hole.png
            description: Pi Hole
            widget:
              type: pihole
              url: http://${PIHOLE_URL}
              key: ${PIHOLE_TOKEN}
        # - Portainer:
        #     href: https://portainer.${SECRET_DOMAIN}
        #     icon: portainer.png
        #     description: Portainer Unraid
        #     widget:
        #       type: portainer
        #       url: http://${NAS_IP}:9000
        #       env: 1
        #       key: ${PORTAINER_TOKEN}
    # - Minecraft:
    #     - Vibecraft:
    #         icon: minecraft.png
    #         server: smurf-raid
    #         container: vibecraft
    #         widget:
    #           type: minecraft
    #           url: udp://${NAS_IP}:25565
    #     - Skyblock:
    #         icon: minecraft.png
    #         widget:
    #           type: minecraft
    #           url: udp://${NAS_IP}:25566
    #     - Create:
    #         icon: minecraft.png
    #         widget:
    #           type: minecraft
    #           url: udp://${NAS_IP}:25567
  bookmarks.yaml: |
    ---
        - Communitcate:
            - Discord:
                - icon: discord.png
                  href: 'https://discord.com/app'
            - Gmail:
                - icon: gmail.png
                  href: 'http://gmail.com'
            - Google Calendar:
                - icon: google-calendar.png
                  href: 'https://calendar.google.com'
            - Outlook:
                - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/outlook.png
                  href: 'https://outlook.com'
        - Media:
            - YouTube:
                - icon: youtube.png
                  href: 'https://youtube.com/feed/subscriptions'
            - Spotify:
                - icon: spotify.png
                  href: 'http://open.spotify.com'
            - Youtube Music:
                - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/youtube-music.png
                  href: 'https://music.youtube.com'
        - Reading:
            - Beyond:
                - icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/beyond.png
                  href: 'https://forums.beyond.ca/search.php?do=getnew&contenttype=vBForum_Post'
            - Reddit:
                - icon: reddit.png
                  href: 'https://reddit.com'
        - Git:
            - k8s-at-home:
                - icon: kubernetes-dashboard.png
                  href: 'https://nanne.dev/k8s-at-home-search/'
            - k3s-home-cluster:
                - icon: github.png
                  href: 'https://github.com/LilDrunkenSmurf/k3s-home-cluster'
  docker.yaml: |
    ---
  kubernetes.yaml: |
    ---
    mode: cluster
