---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.10.9
    enableRbac: true
    env:
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: 3000
            targetPort: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          authentik.home.arpa/enabled: "true"
          nginx.ingress.kubernetes.io/affinity: "cookie"
          nginx.ingress.kubernetes.io/affinity-mode: "persistent"
          nginx.ingress.kubernetes.io/session-cookie-name: "homepage"
          nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
          nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    config:
      useExistingConfigMap: *app
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
