---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
    image:
      repository: ghcr.io/benphelps/homepage
      tag: v0.6.19
    enableRbac: true
    env:
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: 3000
            targetPort: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    config:
      useExistingConfigMap: *app
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        memory: 500Mi
