---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetaData:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/instance: *app
  path: ./kubernetes/apps/downloads/radarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
