---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-plex
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/plex/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
