---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/navidrome/navidrome
      tag: 0.49.3

    env:
      ND_DATAFOLDER: /data
      ND_ENABLEDOWNLOADS: "true"
      ND_ENABLEEXTERNALSERVICES: "false"
      ND_ENABLESHARING: "false"
      ND_ENABLESTARRATING: "false"
      ND_LOGLEVEL: info
      ND_MUSICFOLDER: /music
      ND_PORT: &port 4533
      ND_SCANSCHEDULE: 30m

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
        hosts:
          - host: &host navidrome.${SECRET_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      music-main:
        enabled: true
        mountPath: /music
        path: ${SECRET_NFS_DATA}/music
        server: ${NAS_IP}
        type: nfs
        readOnly: true

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 1234
      fsGroupChangePolicy: "OnRootMismatch"

    resources:
      requests:
        cpu: 5m
        memory: 799M

    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
