---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autoscan
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
        configmap.reloader.stakater.com/reload: &configmap autoscan-configmap
        plex-token.reloader.stakater.com/reload: &plex-token autoscan-plex-token
    image:
      repository: ghcr.io/hotio/autoscan
      tag: release-1.3.0
    env:
      TZ: "${TZ}"
      PUID: 568
      PGID: 568
      UMASK: 002
    service:
      main:
        ports:
          http:
            port: 3030
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: autoscan.png
          gethomepage.dev/name: Autoscan
          gethomepage.dev/group: Downloads
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
    persistence:
      media:
        enabled: true
        existingClaim: downloads
        mountPath: /data
      config-file:
        enabled: true
        type: configMap
        name: *configmap
        subPath: config.yml
        mountPath: /config/config.yml
        readOnly: true
      plex-token:
        enabled: true
        type: configMap
        name: *plex-token
        subPath: plex.token
        mountPath: /config/plex.token
        readOnly: true
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
