---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: immich-dragonfly
    - name: immich-postgres
    - name: longhorn
      namespace: storage
  values:
    controllers:
      immich-server:
        annotations:
          configmap.reloader.stakater.com/reload: &configmap immich-configmap
          secret.reloader.stakater.com/reload: &secret immich-secret
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.115.0
            envFrom:
              - configMapRef:
                  name: *configmap
              - secretRef:
                  name: *secret
            probes:
              liveness: &probes
                enabled: true
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 249M

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3001
      lb:
        controller: *app
        type: LoadBalancer
        ports:
          lb:
            port: 3001

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: immich.png
          gethomepage.dev/name: Immich
          gethomepage.dev/group: Media
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/proxy-body-size: "0" # Remove default limit of 100M
        hosts:
          - host: &host photos.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      upload:
        type: nfs
        server: ${NAS_IP}
        path: ${SECRET_IMMICH_SHARE}
        globalMounts:
          - path: /usr/src/app/upload
