---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autobrr
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
        configmap.reloader.stakater.com/reload: &configmap autobrr-configmap
    image:
      repository: ghcr.io/autobrr/autobrr
      tag: v1.27.0
    env:
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: 7474
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host autobrr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: autobrr-tls
            hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: longhorn
    persistence:
      config-file:
        enabled: true
        type: configMap
        name: *configmap
        subPath: config.toml
        mountPath: /config/config.toml
        readOnly: true
    podLabels:
      vpn/ovpn: "true"
    resources:
      requests:
        memory: 250Mi
        cpu: 10m
